---
title: Spreek hardop met de tekst-naar-spraak-uitbreiding
hero_image: images/banner.png
description: Gebruik de tekst-naar-spraak-uitbreiding om sprites hardop te laten spreken
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Spreek hardop met de tekst-naar-spraak-uitbreiding
