---
title: Make a sprite talk with the Text to Speech extension
hero_image: प्रतिमा / banner.png
description: Using the Text to Speech extension to make sprites speak out loud
version: 0
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Make a sprite talk with the Text to Speech extension
