---
title: Yenza intetho ye-sprite kunye nolwandiso lweSibhalo kwiNtetho
hero_image: images/banner.png
description: Ukusebenzisa iSibhalo kwiNtetho ukwandiswa ukwenza i-sprites ithethele phezulu
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Yenza intetho ye-sprite kunye nolwandiso lweSibhalo kwiNtetho
