---
title: Napravi da lik priča koristeći proširenje Tekst u govor
hero_image: images/banner.png
description: Korištenje proširenja Tekst u govor kako bi likovi govorili naglas
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Napravi da lik priča koristeći proširenje Tekst u govor
