---
title: Haz que un sprite hable con la extensión Texto a voz
hero_image: images/banner.png
description: Usar la extensión Texto a voz para hacer que los sprites hablen en voz alta
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Haz que un sprite hable con la extensión Texto a voz
