---
title: Gwneud corlun i siarad gyda'r estyniad Testun i Leferydd
hero_image: images/banner.png
description: Defnyddio'r estyniad Testun i Leferydd i wneud i gorluniau i siarad yn uchel
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Gwneud corlun i siarad gyda'r estyniad Testun i Leferydd
