---
title: Bringe eine Figur zum Sprechen mit der Text-zu-Sprache-Erweiterung
hero_image: images/banner.png
description: Wie du die Text-zu-Sprache-Erweiterung verwendest, um Figuren laut sprechen zu lassen
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Bringe eine Figur zum Sprechen mit der Text-zu-Sprache-Erweiterung
