---
title: Fazer um ator conversar com a extensão Texto para Fala
hero_image: images/banner.png
description: Usando a extensão Texto para Fala para fazer os atores falarem
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Fazer um ator conversar com a extensão Texto para Fala
