---
title: Fes que un personatge parli amb l'extensió de Text a Parla
hero_image: images/banner.png
description: Utilitzar l'extensió de Text a Parla per fer que els personatges parlin en veu alta
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Fes que un personatge parli amb l'extensió de Text a Parla
