---
title: Nauč postavu mluvit pomocí rozšíření Text na hlas
hero_image: images/banner.png
description: Použití rozšíření Text na hlas k tomu, aby postavy mluvily nahlas
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Nauč postavu mluvit pomocí rozšíření Text na hlas
