---
title: Haz que un objeto hable con la extensión Texto a Voz
hero_image: images/banner.png
description: Usar la extensión Texto a Voz para hacer que los objetos hablen en voz alta
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Haz que un objeto hable con la extensión Texto a Voz
