---
title: Make a sprite talk with the Text to Speech extension
hero_image: images/banner.png
description: استخدام ملحق نص الى كلام لجعل الكائنات تتحدث بصوت عالٍ
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Make a sprite talk with the Text to Speech extension
