---
title: Nawiąż rozmowę z duszkiem z rozszerzeniem Tekst na Mowę
hero_image: images / banner.png
description: Używanie rozszerzenia zamiany tekstu na mowę, aby duszki przemówiły
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - 
    title: Spraw żeby duszek mówił wykorzystując rozszerzenie Tekst na Mowę
