---
title: Få en sprajt att prata med tillägget Text till tal
hero_image: images/banner.png
description: Använda "text till tal"-tillägget för att få sprajter att tala högt
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Få en sprajt att prata med tillägget Text till tal
