---
title: Parler à voix haute avec l'extension Synthèse vocale
hero_image: images/banner.png
description: Utiliser l'extension Synthèse vocale pour faire parler les sprites à voix haute.
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Parler à voix haute avec l'extension Synthèse vocale
