---
title: Fai parlare uno sprite con l'estensione Da Testo a Voce
hero_image: images/banner.png
description: Utilizzare l'estensione Da Testo a Voce per far parlare gli sprite ad alta voce
version: 4
listed: false
copyedit: false
last_tested: "2021-03-10"
steps:
  - title: Fai parlare uno sprite con l'estensione Da Testo a Voce
